version: '3'
services:
  api:
    volumes:
      - .:/home/app:cached
      - ./.devcontainer/.bash_history:/root/.bash_history
      - ./.devcontainer/.bashrc:/root/.bashrc
      - ./.vscode/ext/:/root/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
