# Generated by Django 4.0.3 on 2022-04-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='sales_contact',
            new_name='salesmans',
        ),
    ]
